### ISSUE TITLE
BTC Deposit Address is not showing and cannot be created

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [algobasket/PeatioCryptoExchange#20]
in: /funds#/deposits/btc , I can't see my btc address and I can't generate a new one.

why  the address it is empty? any idea what it is going on?

I started : bitcoind and still downloading the blockchain is there is the reason?

when I click in : generate a new deposit address and confirm I get this message bellow.

**it can't generate new address if it hasn't been used.**

thank you.

**Comment by algobasket** [comment]
If you can't create a bitcoin address then it's one of 3 things:

**- Your daemons are not running.**
**- bitcoind is not running**
**- You haven't entered the correct credentials in the currencies.yml configuration file so your Peatio installation cant' connect to bitcoind**

You should be able to figure out which the problem is by tailing log/production.log

**Comment by openbooknoobdeveloper** [comment]
I did:

`bitcoind`

# start all daemons
`bundle exec rake daemons:start`
**ERROR: there is already one or more instance(s) of the program running**

# or start daemon one by one
`bundle exec rake daemon:matching:start`
**ERROR: there is already one or more instance(s) of the program running**



**in currencies.yml** I changed:
rpc: http://testuser:testpass@127.0.0.1:18332



**bitcoin.conf**

```
server=1
daemon=1

# If run on the test network instead of the real bitcoin network
testnet=0

# You must set rpcuser and rpcpassword to secure the JSON-RPC api
# Please make rpcpassword to something secure, `5gKAgrJv8CQr2CGUhjVbBFLSj29HnE6YGXvfykHJzS3k` for example.
# Listen for JSON-RPC connections on <port> (default: 8332 or testnet: 18332)
rpcuser=testuser
rpcpassword=testpass
rpcport=18332

# Notify when receiving coins
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

```


what I am doing wrong?

**Comment by openbooknoobdeveloper** [comment]
the wallet it is running as you can see

 **bitcoin-cli getblockchaininfo**
{```

  "chain": "main",
  "blocks": 194303,
  "headers": 549878,
  "bestblockhash": "0000000000000636aaaa2311022714c37e7951a6008f2543cb45008016c7388f",
  "difficulty": 2190865.970102859,
  "mediantime": 1345190635,
  "verificationprogress": 0.01722410314730224,
  "initialblockdownload": true,
  "chainwork": "0000000000000000000000000000000000000000000000176d47381c4d30a520",
  "size_on_disk": 3065785574,
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": false
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": false
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": false
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "defined",
      "startTime": 1462060800,
      "timeout": 1493596800,
      "since": 0
    },
    "segwit": {
      "status": "defined",
      "startTime": 1479168000,
      "timeout": 1510704000,
      "since": 0
    }
  },
  "warnings": ""
}
```

**Comment by pankaj9310** [comment]
@openbooknoobdeveloper 
check hot wallet and deposit coin log using below command 
tail -f log/peatio\:amqp\:deposit_coin.output 
tail -f log/hot_wallets.rb.output

**Comment by openbooknoobdeveloper** [comment]
@pankaj9310 useful command bro, I wondering is the wallet need to be fully sync to generate the address?

 **tail -f log/peatio:amqp:deposit_coin.output**
```
/home/deploy/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
I, [2018-11-13T07:10:44.485740 #18607]  INFO -- : Received: {"payment_address_id":1,"currency":"btc","locale":"en"}
F, [2018-11-13T07:10:44.487610 #18607] FATAL -- : CoinRPC::ConnectionRefusedError (CoinRPC::ConnectionRefusedError)
/home/deploy/peatio/app/services/coin_rpc.rb:46:in `rescue in http_post_request'
/home/deploy/peatio/app/services/coin_rpc.rb:39:in `http_post_request'
/home/deploy/peatio/app/services/coin_rpc.rb:32:in `handle'
/home/deploy/peatio/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/app/models/worker/deposit_coin_address.rb:14:in `process'
/home/deploy/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
F, [2018-11-13T07:10:44.487697 #18607] FATAL -- : /home/deploy/peatio/app/services/coin_rpc.rb:46:in `rescue in http_post_request'
/home/deploy/peatio/app/services/coin_rpc.rb:39:in `http_post_request'
/home/deploy/peatio/app/services/coin_rpc.rb:32:in `handle'
/home/deploy/peatio/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/app/models/worker/deposit_coin_address.rb:14:in `process'
/home/deploy/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
I, [2018-11-13T07:10:44.488419 #18607]  INFO -- : Received: {"payment_address_id":2,"currency":"eth","locale":"en"}
F, [2018-11-13T07:10:44.499753 #18607] FATAL -- : getaddrinfo: Name or service not known (SocketError)
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/rest-client-1.6.8/lib/restclient/net_http_ext.rb:51:in `request'
/home/deploy/peatio/app/services/coin_rpc.rb:73:in `http_post_request'
/home/deploy/peatio/app/services/coin_rpc.rb:61:in `handle'
/home/deploy/peatio/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/app/models/worker/deposit_coin_address.rb:12:in `process'
/home/deploy/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
F, [2018-11-13T07:10:44.499895 #18607] FATAL -- : /home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `open'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:878:in `connect'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/rest-client-1.6.8/lib/restclient/net_http_ext.rb:51:in `request'
/home/deploy/peatio/app/services/coin_rpc.rb:73:in `http_post_request'
/home/deploy/peatio/app/services/coin_rpc.rb:61:in `handle'
/home/deploy/peatio/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/app/models/worker/deposit_coin_address.rb:12:in `process'
/home/deploy/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'

```


**the command : tail -f log/hot_wallets.rb.output just show me this:**

`hot_wallets.rb: process with pid 18662 started.`

**Comment by pankaj9310** [comment]
@openbooknoobdeveloper 
you have problem in rpc connection 
I, [2018-11-13T07:10:44.485740 #18607]  INFO -- : Received: {"payment_address_id":1,"currency":"btc","locale":"en"}
F, [2018-11-13T07:10:44.487610 #18607] FATAL -- : CoinRPC::ConnectionRefusedError (CoinRPC::ConnectionRefusedError)
are you running bitcoin on same server of different server
if btc are in different server than change config file of btc.
add below line in bitcoin.conf
`rpcallowip=private address of exchange server`

test rpc connection using curl command
`curl -X POST http://username:password@ipaddress:port/ -d '{"jsonrpc":"2.0","id":"0","method":"getinfo"}' -H 'Content-Type: application/json'`

**Comment by openbooknoobdeveloper** [comment]
@pankaj9310  thanks a lot man, everything it is working now. cheers.
