### ISSUE TITLE
Having trouble connecting to Redis

### ISSUE THREAD

**Issue by cipherzzz** [algobasket/PeatioCryptoExchange#43]
I am able going through the production config and am able to see the server, but it seems to crash due to a redis connection issue

![image](https://user-images.githubusercontent.com/33289322/53344089-d0981100-38df-11e9-8001-7d83c81523a9.png)

last 100 lines of `global_state.rb.out`
```
[2019-02-25T14:19:01.501773 #4225] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `read_nonblock'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:49:in `_read_from_socket'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:41:in `gets'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/connection/ruby.rb:273:in `read'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:229:in `block in read'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:220:in `io'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:228:in `read'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `block in call'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:201:in `block (2 levels) in process'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:309:in `ensure_connected'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:191:in `block in process'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:270:in `logging'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:190:in `process'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis/client.rb:96:in `call'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:784:in `block in get'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:37:in `block in synchronize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-3.0.7/lib/redis.rb:783:in `get'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/interface.rb:5:in `get'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:17:in `get'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:169:in `read_entry'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:314:in `block in read'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:519:in `instrument'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.12/lib/active_support/cache.rb:313:in `read'
/home/vagrant/PeatioCryptoExchange/app/models/global.rb:59:in `ticker'
/home/vagrant/PeatioCryptoExchange/lib/daemons/global_state.rb:21:in `block in <top (required)>'
/home/vagrant/PeatioCryptoExchange/lib/daemons/global_state.rb:18:in `each'
/home/vagrant/PeatioCryptoExchange/lib/daemons/global_state.rb:18:in `<top (required)>'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
/home/deploy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
lib/daemons/global_state_ctl:6:in `<main>'
```

redis appears to be up and there isn't a pw configured...
```
deploy@ubuntu-xenial:/home/vagrant/PeatioCryptoExchange$ redis-cli ping
PONG
```

Any ideas with this @algobasket ?

**Comment by cipherzzz** [comment]
nevermind - seems to be working
