### ISSUE TITLE
bundle exec rake assets:precompile - ExecJS::ProgramError: ExecJS::ProgramError

### ISSUE THREAD

**Issue by SpookyPool** [algobasket/PeatioCryptoExchange#87]
I think the title speaks for itself. Getting an error when running ``bundle exec rake assets:precompile``

```spooky@spookypool:~/peatio/Spero-Exchange$ bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
ExecJS::ProgramError: ExecJS::ProgramError
  (in /home/spooky/peatio/Spero-Exchange/app/assets/javascripts/admin.js)
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/execjs-2.2.1/lib/execjs/external_runtime.rb:64:in `extract_result'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/execjs-2.2.1/lib/execjs/external_runtime.rb:29:in `exec'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/uglifier-2.4.0/lib/uglifier.rb:184:in `really_compile'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/uglifier-2.4.0/lib/uglifier.rb:108:in `compile'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/compressing.rb:63:in `block (2 levels) in js_compressor='
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/processor.rb:29:in `call'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/processor.rb:29:in `evaluate'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:197:in `block in evaluate'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:25:in `initialize'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `new'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `build_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/spooky/peatio/Spero-Exchange/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/spooky/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/spooky/.rbenv/versions/2.2.1/bin/rake:33:in `<main>'
Tasks: TOP => assets:precompile```

**Comment by alinetskyi** [comment]
Hi, sorry to hear that you run into issues when trying to launch Peatio.
Please consider checking out our work on top of Peatio.
https://youtu.be/qLjl2csyVPw
