### ISSUE TITLE
Error Trade Executor

### ISSUE THREAD

**Issue by LightBurdenOfficial** [algobasket/PeatioCryptoExchange#88]
```
peatio:amqp:trade_executor:1: process with pid 13600 started.
E, [2019-12-09T07:40:03.350653 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: Got an exception when sending data: Connection reset by peer (Errno::ECONNRESET)
W, [2019-12-09T07:40:03.389317 #13600]  WARN -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: Recovering from a network failure...
E, [2019-12-09T07:43:09.569452 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: Exception in the reader loop: Bunny::NoFinalOctetError: Frame doesn't end with Î as it must, which means the size is miscalculated.
E, [2019-12-09T07:43:09.663245 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: Backtrace: 
E, [2019-12-09T07:43:09.672804 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: 	/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/transport.rb:218:in `read_next_frame'
E, [2019-12-09T07:43:09.673824 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: 	/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:63:in `run_once'
E, [2019-12-09T07:43:09.673944 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: 	/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:33:in `block in run_loop'
E, [2019-12-09T07:43:09.675573 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: 	/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `loop'
E, [2019-12-09T07:43:09.675752 #13600] ERROR -- #<Bunny::Session:47410537240500 guest@127.0.0.1:5672, vhost=/>: 	/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/reader_loop.rb:30:in `run_loop'
/home/deploy/.rbenv/versions/2.2.7/lib/ruby/2.2.0/logger.rb:606:in `rescue in block in write' : log writing failed. caught an unexpected exception in the network loop: Frame doesn't end with Î as it must, which means the size is miscalculated. (StandardWarning)
/home/deploy/.rbenv/versions/2.2.7/lib/ruby/2.2.0/logger.rb:606:in `rescue in block in write' : log writing failed. "\xCE" from ASCII-8BIT to UTF-8 (StandardWarning)
/home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/amq-protocol-1.9.2/lib/amq/protocol/frame.rb:64:in `decode_header': Must be one of [:method, :headers, :body, :heartbeat] (AMQ::Protocol::FrameTypeError)
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/transport.rb:208:in `read_next_frame'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/session.rb:942:in `open_connection'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/session.rb:255:in `start'
	from /home/deploy/peatio/lib/daemons/amqp_daemon.rb:17:in `<top (required)>'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/trade_executor_ctl:17:in `block in <main>'
	from lib/daemons/trade_executor_ctl:7:in `times'
	from lib/daemons/trade_executor_ctl:7:in `<main>'
```

**Comment by alinetskyi** [comment]
Hi, sorry to hear that you run into issues when trying to launch Peatio.
Please consider checking out our work on top of Peatio.
https://youtu.be/qLjl2csyVPw
